name: smart_student_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: any
  build_runner: any
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/kalila.jpg
